"use client"
import { Global } from "./globalStyle"

export const metadata = {
  title: 'ecommerce product page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Global />
      <body>
        {children}
      </body>
    </html>
  )
}
